name: Release
on: [pull_request, push]

jobs:
  checks:
    name: Create a release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
      - name: Download dependencies
        run: flutter pub get
      - name: Build the app
        run: flutter build apk --release --build-number=${{github.run_number}}
      - uses: actions/upload-artifact@v4
        with:
          name: encora-pulse
          path: build/app/outputs/flutter-apk/app-release.apk
